"""Preview-only captions. Explicit SRT timing or clearly labelled estimated phrases."""
import re
import json
from pathlib import Path


def timestamp(seconds):
    ms = round(max(0, seconds) * 1000)
    h, ms = divmod(ms, 3600000)
    m, ms = divmod(ms, 60000)
    s, ms = divmod(ms, 1000)
    return f'{h:02}:{m:02}:{s:02}.{ms:03}'


def parse_srt(text):
    text = text.lstrip('\ufeff').replace('\r\n', '\n').strip()
    cues = []
    pattern = r'(\d+):(\d{2}):(\d{2})[,.](\d{3})'
    def seconds(parts):
        h, m, s, ms = map(int, parts)
        if m >= 60 or s >= 60:
            raise ValueError('Mốc SRT không hợp lệ.')
        return h * 3600 + m * 60 + s + ms / 1000
    for block in re.split(r'\n\s*\n', text):
        lines = block.splitlines()
        if not lines:
            continue
        timing = 1 if lines[0].strip().isdigit() else 0
        if timing >= len(lines):
            raise ValueError('Khối SRT thiếu thời gian.')
        match = re.fullmatch(pattern + r'\s*-->\s*' + pattern + r'\s*', lines[timing].strip())
        if not match:
            raise ValueError('SRT cần mốc HH:MM:SS,mmm --> HH:MM:SS,mmm.')
        start, end = seconds(match.groups()[:4]), seconds(match.groups()[4:])
        if end <= start:
            raise ValueError('Thời điểm kết thúc phải sau bắt đầu.')
        content = '\n'.join(lines[timing + 1:]).strip()
        if content:
            cues.append(dict(start=start, end=end, text=content))
    return sorted(cues, key=lambda c: (c['start'], c['end']))


def estimated_cues(timeline, words_per_cue=10):
    cues = []
    for scene in timeline:
        words = scene.get('subtitle', '').split()
        for offset in range(0, len(words), words_per_cue):
            end = min(len(words), offset + words_per_cue)
            cues.append(dict(start=scene['start'] + scene['duration'] * offset / len(words),
                             end=scene['start'] + scene['duration'] * end / len(words),
                             text=' '.join(words[offset:end])))
    return cues


def active_cues(cues, seconds):
    return [(i, c) for i, c in enumerate(cues) if c['start'] <= seconds < c['end']]


def load_captions(project, timeline):
    from .srt import scenes_to_srt
    project = Path(project)
    custom = project / 'preview_subtitles.srt'
    if custom.exists():
        return parse_srt(custom.read_text(encoding='utf-8-sig')), 'SRT nhập · thời gian tuyệt đối'
    default = project / 'subtitles.srt'
    if default.exists():
        text = default.read_text(encoding='utf-8-sig')
        # Existing autogenerated one-scene paragraphs are not speech alignment.
        scenes_path = project / 'scenes.json'
        scenes = json.loads(scenes_path.read_text(encoding='utf-8')) if scenes_path.exists() else [dict(narration=s['subtitle'], estimated_duration_sec=s['duration']) for s in timeline]
        expected = scenes_to_srt(scenes)
        if text.strip() != expected.strip():
            return parse_srt(text), 'SRT dự án · thời gian tuyệt đối'
    return estimated_cues(timeline), 'Chia câu ước tính · chưa căn theo giọng'
