import copy
import json
import shutil
import zipfile

import pytest

from studio_bridge.project import (SCHEMA, add_cue, contained, export_bundle,
                                   from_preview, read, register, validate, write)
from studio_bridge.kaggle import inspect, prepare, probe, run


def project_fixture(tmp_path):
    root = tmp_path / "project"
    root.mkdir()
    (root / "image.png").write_bytes(b"test-image")
    write(root / "preview_profile.json", {"project_id": "fixture", "aspect_ratio": "9:16", "scenes": [
        {"scene_id": "scene_001", "media": "image.png", "narration": "Xin chào", "estimated_duration_sec": 1, "text_effect": "fade"}]})
    return root, from_preview(root)


def test_roundtrip_bundle_deduplicates_and_excludes_config(tmp_path):
    root, project = project_fixture(tmp_path)
    sfx = root / "pop.wav"; sfx.write_bytes(b"test-audio")
    aid = register(root, project, sfx, "sfx")
    assert register(root, project, sfx, "music") == aid
    add_cue(project, aid, "sfx", "scene_001", duration_s=0.2)
    add_cue(project, aid, "sfx", "scene_001", offset_s=0.4, duration_s=0.2)
    write(root / "studio.project.json", project)
    (root / "config.yaml").write_text("SECRET=fixture", encoding="utf-8")
    bundle = tmp_path / "bundle.zip"
    report = export_bundle(root, bundle)
    assert report["package_ready"] and not report["render_ready"]
    with zipfile.ZipFile(bundle) as z:
        assert "config.yaml" not in z.namelist()
        assert len([n for n in z.namelist() if n.startswith("resources/audio/")]) == 1
        z.extractall(tmp_path / "relocated")  # trusted archive generated by this test
    moved = tmp_path / "relocated"
    assert validate(moved, read(moved / "studio.project.json"))["package_ready"]
    assert len(read(moved / "studio.project.json")["cues"]) == 2
    with pytest.raises(FileExistsError): export_bundle(root, bundle)


@pytest.mark.parametrize("path", ["../key.txt", "/tmp/key.txt", "C:/keys.txt", "a\\b.png"])
def test_path_escape_rejected(tmp_path, path):
    with pytest.raises(ValueError): contained(tmp_path, path)


def test_tamper_missing_and_duplicate_rejected(tmp_path):
    root, project = project_fixture(tmp_path)
    bad = copy.deepcopy(project); bad["scenes"].append(bad["scenes"][0])
    with pytest.raises(ValueError): validate(root, bad)
    source = contained(root, project["assets"][0]["path"])
    source.write_bytes(b"tampered")
    with pytest.raises(ValueError, match="modified"): validate(root, project)
    source.unlink()
    with pytest.raises(ValueError, match="Missing"): validate(root, project)


def test_unknown_effect_preserved_but_blocks_prepare(tmp_path):
    root, project = project_fixture(tmp_path)
    project["effects_required"] = ["optical_motion_blur"]
    write(root / "studio.project.json", project)
    assert "optical_motion_blur" in inspect(root, project)["unsupported"]
    with pytest.raises(ValueError, match="Unsupported required"):
        prepare(root, tmp_path / "build", draft=True)
    assert not (tmp_path / "build").exists()


def test_preview_voice_never_promoted(tmp_path):
    root, project = project_fixture(tmp_path)
    voice = root / "sample.wav"; voice.write_bytes(b"audio")
    project["scenes"][0]["preview_audio_id"] = register(root, project, voice, "preview_narration")
    write(root / "studio.project.json", project)
    with pytest.raises(ValueError, match="final_audio_id"):
        prepare(root, tmp_path / "build")
    assert validate(root, project)["missing_final_voice"] == ["scene_001"]


def test_dangling_cue_and_nan_rejected(tmp_path):
    root, project = project_fixture(tmp_path)
    project["scenes"][0]["duration_s"] = float("nan")
    with pytest.raises(ValueError): validate(root, project)
    project["scenes"][0]["duration_s"] = 1
    project["cues"] = [{"cue_id": "cue", "scene_id": "deleted"}]
    with pytest.raises(ValueError, match="deleted"): validate(root, project)


def test_profile_refresh_preserves_cues_and_invalidates_changed_voice(tmp_path):
    root, project = project_fixture(tmp_path)
    voice = root / "voice.wav"; voice.write_bytes(b"audio")
    project["scenes"][0]["final_audio_id"] = register(root, project, voice, "final_narration")
    write(root / "studio.project.json", project)
    assert from_preview(root)["scenes"][0].get("final_audio_id")
    profile = read(root / "preview_profile.json")
    profile["scenes"][0]["narration"] = "Nội dung mới"
    write(root / "preview_profile.json", profile)
    assert not from_preview(root)["scenes"][0].get("final_audio_id")


def test_output_inside_dataset_rejected(tmp_path):
    root, _ = project_fixture(tmp_path)
    with pytest.raises(ValueError, match="outside"):
        prepare(root, root / "output", draft=True)


@pytest.mark.skipif(not shutil.which("ffmpeg") or not shutil.which("ffprobe"), reason="media tools unavailable")
def test_real_media_reflow_and_flow3_inputs(tmp_path):
    root = tmp_path / "input"; root.mkdir()
    image = root / "still.png"
    voice = root / "voice.wav"
    run(["ffmpeg", "-v", "error", "-f", "lavfi", "-i", "color=c=blue:s=128x128", "-frames:v", "1", image])
    run(["ffmpeg", "-v", "error", "-f", "lavfi", "-i", "sine=frequency=440:duration=1.5", "-ar", "24000", "-ac", "1", voice])
    project = {"schema": SCHEMA, "project_id": "ai-fixture", "producer": "kaggle_ai_video",
               "aspect_ratio": "1:1", "fps": 24, "assets": [], "scenes": [], "cues": [], "effects_required": []}
    aid = register(root, project, image, "still")
    vid = register(root, project, voice, "final_narration")
    project["scenes"] = [{"scene_id": "scene_001", "asset_id": aid, "duration_s": 1,
                          "narration": "Xin chào", "text_effect": "fade", "final_audio_id": vid},
                         {"scene_id": "scene_002", "asset_id": aid, "duration_s": 1, "narration": "", "text_effect": "fade"}]
    register(root, project, voice, "sfx")
    add_cue(project, vid, "sfx", "scene_002", offset_s=0.1, duration_s=0.3)
    write(root / "studio.project.json", project)
    before = {p.relative_to(root).as_posix(): p.read_bytes() for p in root.rglob("*") if p.is_file()}
    output = tmp_path / "prepared"
    report = prepare(root, output)
    assert report["duration_s"] == pytest.approx(2.5, abs=0.02)
    assert report["scenes"][1]["start_s"] == pytest.approx(1.5, abs=0.02)
    assert not report["rendered"]
    assert read(output / "flow2_package.json")["preprocess_speed"] == 1
    audio = read(output / "flow3.project.json")["metadata"]["subtitle_style"]["studio_audio"]
    assert audio[1]["start_s"] == pytest.approx(1.6, abs=0.02)
    streams = probe(output / "working.mp4")["streams"]
    assert streams[0]["width"] == 720
    assert not any(s["codec_type"] == "audio" for s in streams)
    assert before == {p.relative_to(root).as_posix(): p.read_bytes() for p in root.rglob("*") if p.is_file()}
